### PR TITLE
no hover zone

### PR DESCRIPTION
**Pull request by dallmeyer**
this piggybacks off the existing implementation for the helper method we added to mod base to detect hovering

lays the groundwork for #11

we should probably make this a toggle in the progress menu somewhere

### CODE REVIEW

**Comment by Zedb0T** [comment]
One thing I was thinking here that would be interesting would maybe be supporting a few different kinds of hover restrictions. 

- No restriction
- Can hover for a decent amount of time
- Can hover for a short amount of time
- Can't hover at all

**Comment by dallmeyer** [comment]
An alternative to restricting it by time - it would be really easy to limit the number of L1 tricks/taps, since thats basically how the detection is coded

**Comment by Zedb0T** [comment]
> An alternative to restricting it by time - it would be really easy to limit the number of L1 tricks/taps, since thats basically how the detection is coded

Yeah this was how I was intending to suggest to approach this

**Review by Zedb0T — DISMISSED** [review]
Looks good as a baseline, can probably run some init thing to determine the hover amount or something later? Also just a thought, should we be adding some consistent comment everywhere like OG::preserve::this?

**Pull request merged**
